version: "3.8"

networks:
    transcendence_network:
        driver: bridge

services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: ./docker/frontend/Dockerfile
        working_dir: /usr/src/app
        ports:
            - "3000:3000"

    backend:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        container_name: backend
        volumes:
            - ./backend:/volumeBackend
        ports:
            - "8000:8000"
        image: backend
        restart: always
        networks:
            - transcendence_network



