version: "3.8"

networks:
    transcendence_network:
        driver: bridge

volumes:
    node_data:
    client_data:

services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: ./docker/frontend/Dockerfile
        working_dir: /usr/src/app
        volumes:
            - ./frontend:/usr/src/app
        ports:
            - "3000:3000"

    backend:
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        container_name: backend
        volumes:
            - ./backend:/volumeBackend
        ports:
            - "8000:8000"
        image: backend
        restart: always
        networks:
            - transcendence_network

    tezos_node:
        image: tezos/tezos:alphanet
        command: tezos-node
        ports:
            - 8732:8732
        volumes:
            - node_data:/var/run/tezos/node
            - client_data:/var/run/tezos/client

