# Generated by Django 5.0.1 on 2024-03-23 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='empty', max_length=2000)),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('address', models.CharField(default='default', max_length=200)),
                ('contact', models.CharField(default='default', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('address', models.CharField(default='default', max_length=200)),
                ('contact', models.CharField(default='default', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VesselDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100)),
                ('loadingPort', models.CharField(default='default', max_length=200)),
                ('destinationPort', models.CharField(default='default', max_length=200)),
                ('dateOfLoading', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='billOfLading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billOfLadingNumber', models.CharField(default='default', max_length=100)),
                ('termsOfDelivery', models.CharField(default='default', max_length=2000)),
                ('carrierSignature', models.CharField(default='default', max_length=2000)),
                ('specialInstructions', models.CharField(default='default', max_length=2000)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.cargo')),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.consignee')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.shipper')),
                ('vesselDetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.vesseldetails')),
            ],
        ),
    ]
