# Generated by Django 5.0.1 on 2024-03-24 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0002_billoflading_contractaddress'),
        ('dataManagement', '0002_billoflading_contracthash'),
    ]

    operations = [
    ]
