# Generated by Django 5.0.1 on 2024-03-24 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManagement', '0004_remove_billoflading_contracthash_billoflading_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billoflading',
            name='cargo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.cargo'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='consignee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.consignee'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='shipper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.shipper'),
        ),
        migrations.AlterField(
            model_name='billoflading',
            name='vesselDetails',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataManagement.vesseldetails'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='value',
            field=models.CharField(default='0$', max_length=300),
        ),
        migrations.AlterField(
            model_name='vesseldetails',
            name='dateOfLoading',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
